#pragma once

/// \file config.h
/// \brief Configuration model and JSON (de)serialization for the Collector.
///
/// The Collector reads a single config.json file at startup. Every runtime
/// value the Collector needs — ProcMon executable path, dataset/experiment
/// roots, working directory, timeouts and the trigger source URL — is loaded
/// from there. No paths are hardcoded in the code base.
///
/// Relative paths inside config.json are resolved against the directory that
/// contains the config file, so the Collector can be launched from anywhere.

#include <filesystem>
#include <string>

namespace defenderatlas {

/// Thrown when the configuration file is missing or malformed.
class ConfigError : public std::runtime_error {
public:
    explicit ConfigError(const std::string& message) : std::runtime_error(message) {}
};

/// Runtime settings for the Collector.
struct Config {
    /// Path to Procmon64.exe (or Procmon.exe) from Sysinternals.
    std::filesystem::path procmon_path;

    /// Root directory that contains the sample tree to enumerate.
    std::filesystem::path dataset_root;

    /// Root directory that receives per-experiment output directories.
    std::filesystem::path experiment_root;

    /// Directory where triggered samples are placed (the "Downloads" location).
    std::filesystem::path working_directory;

    /// Duration (ms) the completion strategy waits after a trigger fires.
    std::uint64_t trigger_timeout_ms = 8000;

    /// Completion strategy to use: "timeout" or "procmon_activity".
    std::string completion_strategy = "timeout";

    /// ProcMon filter profile applied to the filtered CSV: "minimal",
    /// "extended" or "full".
    std::string procmon_filter_profile = "minimal";

    /// Path to the DefenderAtlas Analyzer executable (defenderatlas_analyzer).
    /// When empty, analysis is skipped and a basic report.md is generated by
    /// the Collector itself.
    std::filesystem::path analyzer_path;

    /// Maximum time (ms) to wait for the analyzer to produce report.md.
    std::uint64_t analyzer_timeout_ms = 60000;

    /// Maximum time (ms) to wait for the trigger worker process to finish
    /// Save() and exit. Independent of trigger_timeout_ms because a slow
    /// Defender/SmartScreen cloud check can make a single worker take seconds.
    std::uint64_t trigger_worker_timeout_ms = 30000;

    /// Source URL reported to IAttachmentExecute::SetSource.
    std::string source_url = "https://example.com/download";

    /// Path to trigger_worker.exe, the short-lived process that runs the
    /// IAttachmentExecute trigger. Resolved relative to the config directory.
    std::filesystem::path trigger_worker_path;

    /// Maximum time (ms) to wait for ProcMon to become ready after launch.
    std::uint64_t procmon_ready_timeout_ms = 15000;

    /// Maximum time (ms) to wait for ProcMon to shut down gracefully.
    std::uint64_t procmon_stop_timeout_ms = 15000;

    /// Maximum time (ms) to wait for a PML -> CSV export.
    std::uint64_t procmon_export_timeout_ms = 120000;
};

/// Return the built-in default configuration (matches config.json template).
Config default_config();

/// Load configuration from \p path, tolerating missing keys by falling back
/// to defaults. Relative paths are resolved against the config file directory.
/// Throws ConfigError on unreadable/malformed files.
Config load_config(const std::filesystem::path& path);

/// Write \p config to \p path as a pretty-printed config.json.
/// Throws ConfigError on write failure.
void save_config(const std::filesystem::path& path, const Config& config);

} // namespace defenderatlas
